### ISSUE TITLE
Nav Bar Security Issue

### ISSUE THREAD

**Issue by majiru** [KCCCDC/cdc-document-manager#1]
On the main page of the website there is a navigation bar is shown based on a JavaScript check, which means with a simple disable of it, you can see the entire bar without having to login.  This is a further issue then just the display, the other php pages do not properly check to see if the person is logged in the begin with.  This means that anyone can visit the /admin.php page and get a look at all the users and files. ![example](http://i.imgur.com/6hPPiZ9.png)  It also seems the entire login system is based of JavaScript, I am hoping we could stream line the code a bit and remove as much dependency on JavaScript as possible.

**Comment by twstagg** [comment]
We should be able to handle this completely server side. Javascript checks will be disabled completely.

**Comment by majiru** [comment]
Hopefully we could completely get rid of the use of Java Script.  I am thinking of perhaps getting rid of the javascript and do everything server side.
