### ISSUE TITLE
User Managment

### ISSUE THREAD

**Issue by majiru** [KCCCDC/cdc-document-manager#3]
Currently, all of the users are being managed by two files, the .password file defining their existence, and the .user file in the file directories that define the access.  This could be migrated over to a sql database, with minimal issues, and would result in better security.

**Comment by twstagg** [comment]
I vote SQLITE

**Comment by majiru** [comment]
We have working SQLITE3 using the PDO php module in the dev branch.  We have both a login and register script working, the register script is mostly for our utility for managing users in early bug testing states.
